# Generated by Django 4.0.3 on 2023-02-22 20:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('realty', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='pub_date',
        ),
        migrations.RemoveField(
            model_name='question',
            name='question_text',
        ),
        migrations.DeleteModel(
            name='Choice',
        ),
    ]
