# Generated by Django 4.0.3 on 2023-03-04 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('realty', '0003_person'),
    ]

    operations = [
        migrations.CreateModel(
            name='Testart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='Заголовок')),
                ('mutetext', models.CharField(max_length=50, verbose_name='Подзаголовок')),
                ('img', models.CharField(max_length=250, verbose_name='Картинка')),
                ('full_text', models.TextField(verbose_name='Статья')),
            ],
        ),
    ]
